services:
  php:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
    environment:
      DB_NAME: leather_store
      DB_USER: habib
      DB_PASSWORD: web
      PGPASSWORD: web
      DB_HOST: database
      DB_PORT: 5432
      ADMIN_USER_NAME: admin
      ADMIN_USER_EMAIL: admini@leather-store.com
      ADMIN_USER_PWD: admin
      URL: http://localhost/
      DEBUG: false
    env_file:
      - .dockerenv
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
  database:
    image: postgres:18.2-alpine3.23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leather_store
      POSTGRES_USER: habib
      POSTGRES_PASSWORD: web
    volumes:
      - database_data:/var/lib/postgresql
volumes:
  database_data:
    driver: local
